services:
  - type: web
    name: chessweb-backend
    runtime: node
    repo: https://github.com/29nls/chessweb
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: CORS_ORIGIN
        value: https://chessweb-nu.vercel.app/
