const openings = [
  // ── e4 e5 (Open Games) ─────────────────────────────
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5'], name: 'Ruy Lopez', eco: 'C60-C99' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4'], name: 'Ruy Lopez, Morphy Defense', eco: 'C70' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7'], name: 'Ruy Lopez, Closed Defense', eco: 'C84-C89' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7', 'Re1'], name: 'Ruy Lopez, Closed (Main Line)', eco: 'C84' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Nxe4'], name: 'Ruy Lopez, Open Defense', eco: 'C80-C83' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'f5'], name: 'Ruy Lopez, Schliemann Defense', eco: 'C63' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Nge7'], name: 'Ruy Lopez, Cozio Defense', eco: 'C60' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'g6'], name: 'Ruy Lopez, Steinitz Defense deferred', eco: 'C70' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Bc5'], name: 'Ruy Lopez, Classical Defense', eco: 'C64' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'd6'], name: 'Ruy Lopez, Steinitz Defense', eco: 'C62' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4'], name: 'Italian Game', eco: 'C50-C54' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5'], name: 'Giuoco Piano', eco: 'C50' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'c3', 'Nf6', 'd4', 'exd4', 'e5'], name: 'Italian Game, Main Line', eco: 'C54' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'b4'], name: 'Evans Gambit', eco: 'C51-C52' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6'], name: 'Two Knights Defense', eco: 'C55-C59' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'Ng5', 'd5', 'exd5', 'Na5'], name: 'Two Knights, Fritz Variation', eco: 'C57' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'Ng5', 'd5', 'exd5', 'Nxd5'], name: 'Two Knights, Polerio Defense', eco: 'C58' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Nxd4'], name: 'Scotch Game', eco: 'C45' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Bc4'], name: 'Scotch Gambit', eco: 'C44' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Nc3'], name: 'Four Knights Game', eco: 'C47-C49' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Nc3', 'Nf6'], name: 'Four Knights Game (symmetrical)', eco: 'C47' },
  { moves: ['e4', 'e5', 'f4'], name: 'King\'s Gambit', eco: 'C30-C39' },
  { moves: ['e4', 'e5', 'f4', 'exf4'], name: 'King\'s Gambit Accepted', eco: 'C33-C39' },
  { moves: ['e4', 'e5', 'f4', 'd5'], name: 'King\'s Gambit Declined, Falkbeer Countergambit', eco: 'C31' },
  { moves: ['e4', 'e5', 'Nf3', 'd6'], name: 'Philidor Defense', eco: 'C41' },
  { moves: ['e4', 'e5', 'Nf3', 'f5'], name: 'Latvian Gambit', eco: 'C40' },
  { moves: ['e4', 'e5', 'Nf3', 'Nf6'], name: 'Petrov\'s Defense', eco: 'C42-C43' },
  { moves: ['e4', 'e5', 'Nf3', 'Nf6', 'Nxe5', 'd6', 'Nf3', 'Nxe4'], name: 'Petrov\'s, Classical Attack', eco: 'C42' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'c3', 'Nf6', 'd4', 'exd4', 'cxd4', 'Bb6'], name: 'Italian, Main Line Greco', eco: 'C54' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nd4'], name: 'Italian, Blackburne Shilling', eco: 'C50' },
  { moves: ['e4', 'e5', 'Nc3'], name: 'Vienna Game', eco: 'C25-C29' },
  { moves: ['e4', 'e5', 'Bc4'], name: 'Bishop\'s Opening', eco: 'C23-C24' },
  { moves: ['e4', 'e5', 'd4', 'exd4', 'c3'], name: 'Danish Gambit', eco: 'C21' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'c3'], name: 'Ponziani Opening', eco: 'C44' },

  // ── e4 c5 (Sicilian Defense) ────────────────────────
  { moves: ['e4', 'c5'], name: 'Sicilian Defense', eco: 'B20-B99' },
  { moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3'], name: 'Sicilian, Open', eco: 'B56' },
  { moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6'], name: 'Sicilian, Najdorf', eco: 'B90-B99' },
  { moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'e6'], name: 'Sicilian, Scheveningen', eco: 'B80-B89' },
  { moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'g6'], name: 'Sicilian, Dragon', eco: 'B70-B79' },
  { moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'e5'], name: 'Sicilian, Boleslavsky', eco: 'B60' },
  { moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'Nc6'], name: 'Sicilian, Classical', eco: 'B56-B59' },
  { moves: ['e4', 'c5', 'Nf3', 'e6', 'd4', 'cxd4', 'Nxd4'], name: 'Sicilian, Taimanov / Kan', eco: 'B40-B49' },
  { moves: ['e4', 'c5', 'Nf3', 'e6', 'd4', 'cxd4', 'Nxd4', 'Nc6'], name: 'Sicilian, Taimanov', eco: 'B46' },
  { moves: ['e4', 'c5', 'Nf3', 'e6', 'd4', 'cxd4', 'Nxd4', 'a6'], name: 'Sicilian, Kan', eco: 'B41-B43' },
  { moves: ['e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4'], name: 'Sicilian, Open (Nc6)', eco: 'B30-B39' },
  { moves: ['e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'g6'], name: 'Sicilian, Accelerated Dragon', eco: 'B34-B39' },
  { moves: ['e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'e6'], name: 'Sicilian, Taimanov (Nc6)', eco: 'B45' },
  { moves: ['e4', 'c5', 'c3'], name: 'Sicilian, Alapin (c3)', eco: 'B22' },
  { moves: ['e4', 'c5', 'Nc3'], name: 'Sicilian, Closed', eco: 'B23-B26' },
  { moves: ['e4', 'c5', 'f4'], name: 'Sicilian, Grand Prix Attack', eco: 'B21' },
  { moves: ['e4', 'c5', 'b4'], name: 'Sicilian, Wing Gambit', eco: 'B20' },
  { moves: ['e4', 'c5', 'Nf3', 'g6', 'd4', 'cxd4', 'Nxd4', 'Bg7'], name: 'Sicilian, Hyper-Accelerated Dragon', eco: 'B27' },

  // ── e4 e6 (French Defense) ──────────────────────────
  { moves: ['e4', 'e6'], name: 'French Defense', eco: 'C00-C19' },
  { moves: ['e4', 'e6', 'd4', 'd5'], name: 'French Defense, Classical', eco: 'C10' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'e5'], name: 'French Defense, Advance Variation', eco: 'C02' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nd2'], name: 'French Defense, Tarrasch Variation', eco: 'C03-C06' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'Nf6', 'Bg5'], name: 'French Defense, Classical Variation', eco: 'C11' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'Nf6', 'e5'], name: 'French Defense, Steinitz Variation', eco: 'C11' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'Bb4'], name: 'French Defense, Winawer Variation', eco: 'C15-C19' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'dxe4'], name: 'French Defense, Rubinstein Variation', eco: 'C10' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'exd5', 'exd5'], name: 'French Defense, Exchange Variation', eco: 'C01' },

  // ── e4 c6 (Caro-Kann Defense) ──────────────────────
  { moves: ['e4', 'c6'], name: 'Caro-Kann Defense', eco: 'B10-B19' },
  { moves: ['e4', 'c6', 'd4', 'd5'], name: 'Caro-Kann, Classical', eco: 'B10' },
  { moves: ['e4', 'c6', 'd4', 'd5', 'e5', 'Bf5'], name: 'Caro-Kann, Advance Variation', eco: 'B12' },
  { moves: ['e4', 'c6', 'd4', 'd5', 'Nc3', 'dxe4', 'Nxe4'], name: 'Caro-Kann, Classical Variation', eco: 'B18' },
  { moves: ['e4', 'c6', 'd4', 'd5', 'Nd2', 'dxe4', 'Nxe4'], name: 'Caro-Kann, Karpov Variation', eco: 'B17' },
  { moves: ['e4', 'c6', 'd4', 'd5', 'exd5', 'cxd5'], name: 'Caro-Kann, Exchange Variation', eco: 'B13' },
  { moves: ['e4', 'c6', 'd4', 'd5', 'Nc3', 'dxe4', 'Nxe4', 'Nd7'], name: 'Caro-Kann, Classical (Nd7)', eco: 'B19' },

  // ── e4 d5 (Scandinavian Defense) ────────────────────
  { moves: ['e4', 'd5'], name: 'Scandinavian Defense', eco: 'B01' },
  { moves: ['e4', 'd5', 'exd5', 'Qxd5', 'Nc3', 'Qa5'], name: 'Scandinavian, Main Line', eco: 'B01' },
  { moves: ['e4', 'd5', 'exd5', 'Nf6'], name: 'Scandinavian, Modern (Nf6)', eco: 'B01' },
  { moves: ['e4', 'd5', 'exd5', 'c6'], name: 'Scandinavian, Icelandic Gambit', eco: 'B01' },

  // ── e4 Nf6 (Alekhine Defense) ───────────────────────
  { moves: ['e4', 'Nf6'], name: 'Alekhine\'s Defense', eco: 'B02-B05' },
  { moves: ['e4', 'Nf6', 'e5', 'Nd5'], name: 'Alekhine\'s, Modern Variation', eco: 'B03' },
  { moves: ['e4', 'Nf6', 'e5', 'Nd5', 'd4', 'd6', 'Nf3', 'Bg4'], name: 'Alekhine\'s, Main Line', eco: 'B04' },

  // ── e4 g6 (Pirc / Modern) ───────────────────────────
  { moves: ['e4', 'g6'], name: 'Modern Defense', eco: 'B06' },
  { moves: ['e4', 'd6'], name: 'Pirc Defense', eco: 'B07-B09' },
  { moves: ['e4', 'd6', 'd4', 'Nf6', 'Nc3', 'g6'], name: 'Pirc, Classical', eco: 'B08' },

  // ── d4 d5 (Closed Games) ────────────────────────────
  { moves: ['d4', 'd5'], name: 'Queen\'s Pawn Game', eco: 'D00-D99' },
  { moves: ['d4', 'd5', 'c4'], name: 'Queen\'s Gambit', eco: 'D06-D69' },
  { moves: ['d4', 'd5', 'c4', 'dxc4'], name: 'Queen\'s Gambit Accepted', eco: 'D20-D29' },
  { moves: ['d4', 'd5', 'c4', 'e6'], name: 'Queen\'s Gambit Declined', eco: 'D30-D69' },
  { moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5'], name: 'QGD, Classical Variation', eco: 'D64-D67' },
  { moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Be7'], name: 'QGD, Orthodox Defense', eco: 'D60' },
  { moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5', 'Nbd7'], name: 'QGD, Cambridge Springs', eco: 'D52' },
  { moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bf4'], name: 'QGD, London System (early)', eco: 'D30' },
  { moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'c5'], name: 'QGD, Semi-Tarrasch', eco: 'D40-D42' },
  { moves: ['d4', 'd5', 'c4', 'c6'], name: 'Slav Defense', eco: 'D10-D19' },
  { moves: ['d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'dxc4'], name: 'Slav Defense, Accepted', eco: 'D10' },
  { moves: ['d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'a6'], name: 'Slav Defense, Chameleon', eco: 'D15' },
  { moves: ['d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'e3', 'Bf5'], name: 'Slav Defense, Quiet Variation', eco: 'D12' },
  { moves: ['d4', 'd5', 'c4', 'c6', 'Nc3'], name: 'Slav Defense (Nc3)', eco: 'D10' },
  { moves: ['d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'e6'], name: 'Semi-Slav Defense', eco: 'D43-D49' },
  { moves: ['d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'e6', 'e3'], name: 'Semi-Slav, Meran', eco: 'D47' },
  { moves: ['d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'e6', 'Bg5'], name: 'Semi-Slav, Anti-Meran', eco: 'D44' },
  { moves: ['d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'e3', 'e6', 'Nbd2', 'Nbd7'], name: 'Slav, Meran (quiet)', eco: 'D43' },
  { moves: ['d4', 'd5', 'Bf4'], name: 'London System', eco: 'D00' },
  { moves: ['d4', 'd5', 'Nf3', 'Nf6', 'Bf4'], name: 'London System (Classical)', eco: 'D00' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'e3'], name: 'QGA, Main Line', eco: 'D21' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'e4'], name: 'QGA, Central Variation', eco: 'D22' },
  { moves: ['d4', 'd5', 'Nc3', 'Nf6', 'Bg5'], name: 'Richter-Veresov Attack', eco: 'D01' },
  { moves: ['d4', 'd5', 'c4', 'c5'], name: 'Symmetrical English (via d4)', eco: 'D06' },
  { moves: ['d4', 'd5', 'e3', 'Nf6', 'Bd3'], name: 'Stonewall Attack', eco: 'D00' },
  { moves: ['d4', 'd5', 'c4', 'Nc6'], name: 'QGD, Chigorin Defense', eco: 'D07' },

  // ── d4 Nf6 (Indian Defenses) ────────────────────────
  { moves: ['d4', 'Nf6'], name: 'Indian Game', eco: 'A40-A79, D70-D99, E00-E99' },
  { moves: ['d4', 'Nf6', 'c4', 'g6'], name: 'King\'s Indian Defense (KID)', eco: 'E60-E99' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6'], name: 'KID, Classical Variation', eco: 'E90' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'Nf3'], name: 'KID, Main Line', eco: 'E90' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'f4'], name: 'KID, Four Pawns Attack', eco: 'E76' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'Be2', 'O-O', 'Nf3', 'e5'], name: 'KID, Mar del Plata', eco: 'E97' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'h3'], name: 'KID, Makogonov Variation', eco: 'E90' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'Nf3', 'Bg7', 'g3'], name: 'King\'s Indian, Fianchetto Variation', eco: 'E60' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5'], name: 'Grünfeld Defense', eco: 'D70-D99' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5', 'cxd5', 'Nxd5', 'e4', 'Nxc3', 'bxc3', 'Bg7'], name: 'Grünfeld, Exchange Variation', eco: 'D85' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'Nf3', 'Bg7', 'g3', 'd5'], name: 'Grünfeld, Fianchetto Variation', eco: 'D70' },
  { moves: ['d4', 'Nf6', 'c4', 'e6'], name: 'Indian Defense (e6)', eco: 'E00-E59' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4'], name: 'Nimzo-Indian Defense', eco: 'E20-E59' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'e3'], name: 'Nimzo-Indian, Rubinstein Variation', eco: 'E41' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'Qc2'], name: 'Nimzo-Indian, Classical Variation', eco: 'E32-E39' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'Qc2', 'd5', 'a3', 'Bxc3+', 'Qxc3'], name: 'Nimzo-Indian, Classical Main Line', eco: 'E32' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'Nf3'], name: 'Queen\'s Indian Defense (QID)', eco: 'E12-E19' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6'], name: 'Queen\'s Indian Defense', eco: 'E12' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'Bb4+'], name: 'Bogo-Indian Defense', eco: 'E11' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'g3'], name: 'Catalan Opening', eco: 'E04-E09' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'g3', 'd5', 'Bg2', 'Be7', 'Nf3', 'O-O', 'O-O', 'dxc4'], name: 'Catalan, Open Variation', eco: 'E05' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'g3', 'd5', 'Bg2', 'Be7', 'Nf3', 'O-O', 'O-O', 'c6'], name: 'Catalan, Closed Variation', eco: 'E06' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'g3', 'd5', 'Bg2'], name: 'Catalan, Main Lines', eco: 'E04' },
  { moves: ['d4', 'Nf6', 'c4', 'b6'], name: 'Queen\'s Indian Defense (early b6)', eco: 'E12' },
  { moves: ['d4', 'Nf6', 'Nf3', 'g6'], name: 'King\'s Indian, Fianchetto (without c4)', eco: 'A49' },
  { moves: ['d4', 'Nf6', 'c4', 'c5'], name: 'Benoni Defense', eco: 'A56-A79' },
  { moves: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'e6'], name: 'Modern Benoni', eco: 'A60' },
  { moves: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'b5'], name: 'Benko Gambit', eco: 'A57' },
  { moves: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'e6', 'Nc3', 'exd5', 'cxd5', 'd6', 'e4', 'g6'], name: 'Modern Benoni, Main Line', eco: 'A67' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6', 'g3', 'Bb7', 'Bg2', 'Be7', 'O-O', 'O-O'], name: 'Queen\'s Indian, Main Line', eco: 'E12' },

  // ── Dutch Defense ────────────────────────────────────
  { moves: ['d4', 'f5'], name: 'Dutch Defense', eco: 'A80-A99' },
  { moves: ['d4', 'f5', 'g3', 'Nf6', 'Bg2', 'g6'], name: 'Dutch, Leningrad Variation', eco: 'A87-A89' },
  { moves: ['d4', 'f5', 'c4', 'Nf6', 'g3', 'e6', 'Bg2'], name: 'Dutch, Classical Variation', eco: 'A84' },
  { moves: ['d4', 'f5', 'g3', 'Nf6', 'Bg2', 'e6', 'Nf3', 'Be7', 'O-O', 'O-O', 'c4'], name: 'Dutch, Main Line', eco: 'A80' },
  { moves: ['d4', 'f5', 'Bf4'], name: 'Dutch, Stonewall', eco: 'A80' },

  // ── Other First Moves ────────────────────────────────
  { moves: ['c4'], name: 'English Opening', eco: 'A10-A39' },
  { moves: ['c4', 'e5'], name: 'English, Symmetrical (e5)', eco: 'A30' },
  { moves: ['c4', 'e5', 'Nc3', 'Nf6', 'g3', 'Bb4'], name: 'English, Kramnik-Shirov', eco: 'A29' },
  { moves: ['c4', 'e5', 'Nc3', 'Nf6', 'Nf3', 'Nc6'], name: 'English, Four Knights', eco: 'A28' },
  { moves: ['c4', 'e5', 'g3', 'Nf6', 'Bg2', 'c6'], name: 'English, King\'s English', eco: 'A20' },
  { moves: ['c4', 'c5'], name: 'English, Symmetrical', eco: 'A30-A39' },
  { moves: ['c4', 'Nf6', 'Nc3', 'e5'], name: 'English, Mikenas-Carls', eco: 'A18' },
  { moves: ['c4', 'e6'], name: 'English, Agincourt Defense', eco: 'A10' },
  { moves: ['c4', 'Nf6', 'Nf3', 'c5'], name: 'English, Anglo-Indian', eco: 'A15' },
  { moves: ['Nf3'], name: 'Reti Opening', eco: 'A04-A09' },
  { moves: ['Nf3', 'd5', 'c4'], name: 'Reti, Main Line', eco: 'A09' },
  { moves: ['Nf3', 'Nf6', 'c4', 'g6', 'b4'], name: 'Reti, Polish Variation', eco: 'A04' },
  { moves: ['g3'], name: 'King\'s Fianchetto', eco: 'A00' },
  { moves: ['b3'], name: 'Nimzo-Larsen Attack', eco: 'A01' },
  { moves: ['b3', 'd5', 'Bb2', 'c5', 'e3'], name: 'Nimzo-Larsen, Main Line', eco: 'A01' },
  { moves: ['f4'], name: 'Bird\'s Opening', eco: 'A02-A03' },
  { moves: ['f4', 'd5', 'Nf3', 'Nf6', 'g3'], name: 'Bird\'s, Main Line', eco: 'A03' },
  { moves: ['Nc3'], name: 'Dunst Opening', eco: 'A00' },
  { moves: ['b4'], name: 'Polish Opening (Sokolsky)', eco: 'A00' },
];

export default openings;
